version: "3.5"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.2-java8
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.2

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    container_name: datanode1
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.3

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    container_name: datanode2
    ports:
      - 9865:9864
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.4

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    container_name: datanode3
    ports:
      - 9866:9864
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.5
  
  hbase:
    image: xitric/hbase-master:latest
    container_name: hbase
    ports:
      - 16000:16000
      - 16010:16010
      - 2888:2888
      - 3888:3888
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zoo:2181"
    env_file:
      - ./hbase.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.20
  
  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - zoo_data:/data
    networks:
      cscourse:
        ipv4_address: 172.200.0.21
  
  region1:
    image: xitric/hbase-region:latest
    container_name: region1
    hostname: region1
    environment:
      HBASE_CONF_hbase_regionserver_hostname: region1
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zoo:2181 hbase:16010"
    env_file:
      - ./hadoop.env
      - ./hbase.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.22
  
  region2:
    image: xitric/hbase-region:latest
    container_name: region2
    hostname: region2
    environment:
      HBASE_CONF_hbase_regionserver_hostname: region2
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zoo:2181 hbase:16010"
    env_file:
      - ./hadoop.env
      - ./hbase.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.23
  
  region3:
    image: xitric/hbase-region:latest
    container_name: region3
    hostname: region3
    environment:
      HBASE_CONF_hbase_regionserver_hostname: region3
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 zoo:2181 hbase:16010"
    env_file:
      - ./hadoop.env
      - ./hbase.env
    networks:
      cscourse:
        ipv4_address: 172.200.0.24
  
  mysql:
    image: xitric/sfdb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      cscourse:
        ipv4_address: 172.200.0.7

networks:
  cscourse:
    name: hadoop
    ipam:
      config:
        - subnet: 172.200.0.0/24

volumes:
  hadoop_namenode:
    name: namenode
  hadoop_datanode1:
    name: datanode1
  hadoop_datanode2:
    name: datanode2
  hadoop_datanode3:
    name: datanode3
  zoo_data:
    name: zookeeper
  mysql_data:
    name: mysql
